const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];

const STORAGE = { users: 'personal_ca_users_v2', session: 'personal_ca_session_v2', theme: 'personal_ca_theme_v2' };
const countryMeta = {
  BD: { name:'Bangladesh', symbol:'৳', source:'https://nbr.gov.bd/taxtypes/income-tax/income-tax-paripatra/eng', slabs:[[350000,0],[100000,0.05],[300000,0.10],[400000,0.15],[500000,0.20],[Infinity,0.25]], standardDeduction:0 },
  IN: { name:'India', symbol:'₹', source:'https://incometaxindia.gov.in/pages/tools/income-tax-calculator.aspx', slabs:[[300000,0],[300000,0.05],[300000,0.10],[300000,0.15],[300000,0.20],[300000,0.25],[Infinity,0.30]], standardDeduction:50000 },
  US: { name:'USA', symbol:'$', source:'https://www.irs.gov/filing/federal-income-tax-rates-and-brackets', slabs:[[11600,0.10],[35550,0.12],[53375,0.22],[100525,0.24],[91425,0.32],[487450,0.35],[Infinity,0.37]], standardDeduction:14600 }
};
const laws = {
  BD:[['Salary income','Employment income, allowances, eligible exemptions and investment rebate rules are important for salaried taxpayers.',countryMeta.BD.source],['Business income','Business taxpayers usually need revenue, cost, expense and asset information.',countryMeta.BD.source],['Investment rebate','Eligible investment may create rebate opportunities under applicable Bangladesh rules.',countryMeta.BD.source]],
  IN:[['Old vs new regime','India taxpayers may need to compare regimes where deductions apply differently.',countryMeta.IN.source],['Salary deductions','Standard deduction, HRA, 80C, 80D and other items may matter depending on facts.',countryMeta.IN.source],['Capital gains','Investments may create separate tax treatment, holding-period rules and reporting needs.',countryMeta.IN.source]],
  US:[['Filing status','Filing status, standard deduction and credits heavily affect federal income tax.',countryMeta.US.source],['Itemized deductions','Some taxpayers compare itemized deductions with the standard deduction.',countryMeta.US.source],['Retirement/HSA','Eligible retirement and HSA contributions may reduce taxable income.',countryMeta.US.source]]
};
const charityLinks = {BD:'https://nbr.gov.bd/', IN:'https://www.incometax.gov.in/iec/foportal/', US:'https://www.irs.gov/charities-non-profits'};
const investLinks = {BD:'https://www.bb.org.bd/', IN:'https://www.nsiindia.gov.in/', US:'https://www.treasurydirect.gov/'};
let currentResult = null;

function load(key, fallback){ try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback} }
function save(key, val){ localStorage.setItem(key, JSON.stringify(val)); }
function users(){ return load(STORAGE.users, []); }
function session(){ return load(STORAGE.session, null); }
function currentUser(){ const s=session(); return s ? users().find(u=>u.id===s.userId) : null; }
function money(v, c){ return c.symbol + Number(Math.max(0,v||0)).toLocaleString(undefined,{maximumFractionDigits:0}); }
async function sha256(text){ const data = new TextEncoder().encode(text); const hash = await crypto.subtle.digest('SHA-256', data); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
function id(){ return crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random()); }
function toast(msg, type='info'){ const el=$('#authMessage'); if(el){el.textContent=msg; el.style.color= type==='bad'?'var(--danger)': type==='ok'?'var(--primary)':'var(--warning)';} }

function setTheme(mode){ document.body.classList.toggle('light', mode==='light'); $('#themeToggle').textContent = mode==='light'?'☀️':'🌙'; save(STORAGE.theme, mode); }
function openAuth(tab='login'){ switchAuth(tab); $('#authDialog').showModal(); setTimeout(()=>$('#'+(tab==='login'?'loginUsername':'regFullName'))?.focus(),50); }
function closeAuth(){ $('#authDialog').close(); toast(''); }
function switchAuth(tab){ $$('.auth-tabs .tab').forEach(b=>b.classList.toggle('active', b.dataset.authTab===tab)); $('#loginForm').classList.toggle('active', tab==='login'); $('#registerForm').classList.toggle('active', tab==='register'); $('#authTitle').textContent = tab==='login'?'Login to continue':'Create your Personal CA account'; toast(''); }

function updateAccountUI(){ const u=currentUser(); const badge=$('#userBadge'); if(u){ badge.classList.remove('hidden'); badge.innerHTML=`<small>Logged in as</small><strong>${u.fullName}</strong><small>@${u.username} · ${u.occupation}</small>`; $('#openAuth').textContent='Account'; $('#openAuthLarge').textContent='Open profile dashboard'; $('#logoutBtn').classList.remove('hidden'); $('#accountHint').textContent='Your calculations can now be saved to your private profile in this browser.'; } else { badge.classList.add('hidden'); $('#openAuth').textContent='Login'; $('#openAuthLarge').textContent='Open login / registration'; $('#logoutBtn').classList.add('hidden'); $('#accountHint').textContent='Login requires username and password. Register once to unlock report history.'; } }

async function register(e){ e.preventDefault(); const fullName=$('#regFullName').value.trim(), occupation=$('#regOccupation').value.trim(), username=$('#regUsername').value.trim().toLowerCase(), email=$('#regEmail').value.trim().toLowerCase(), pass=$('#regPassword').value, confirm=$('#regConfirm').value; if(pass!==confirm) return toast('Passwords do not match. Please double-check.', 'bad'); if(pass.length<6) return toast('Password must be at least 6 characters.', 'bad'); const all=users(); if(all.some(u=>u.username===username)) return toast('That username is already taken.', 'bad'); if(all.some(u=>u.email===email)) return toast('That email is already registered.', 'bad'); const user={id:id(),fullName,occupation,username,email,passwordHash:await sha256(pass),createdAt:new Date().toISOString(),reports:[]}; all.push(user); save(STORAGE.users, all); save(STORAGE.session,{userId:user.id,loggedInAt:new Date().toISOString()}); toast('Account created successfully. Opening your profile...', 'ok'); updateAccountUI(); renderProfile(); setTimeout(()=>{closeAuth(); openProfile();},450); }
async function login(e){ e.preventDefault(); const username=$('#loginUsername').value.trim().toLowerCase(), pass=$('#loginPassword').value; const u=users().find(x=>x.username===username); if(!u || u.passwordHash!==await sha256(pass)) return toast('Invalid username or password.', 'bad'); save(STORAGE.session,{userId:u.id,loggedInAt:new Date().toISOString()}); toast('Login successful. Opening profile...', 'ok'); updateAccountUI(); renderProfile(); setTimeout(()=>{closeAuth(); openProfile();},350); }
function logout(){ localStorage.removeItem(STORAGE.session); updateAccountUI(); $('#profilePage').classList.add('hidden'); document.body.style.overflow=''; }

function getQuestions(country){ const c=countryMeta[country]; const common=`<div class="two-col"><label>Tax year<select name="taxYear"><option>2025-2026</option><option>2024-2025</option><option>2023-2024</option></select></label><label>Occupation type<select name="occupationType"><option value="salaried">Salaried / job holder</option><option value="business">Business owner / self-employed</option><option value="freelancer">Freelancer / contractor</option><option value="investor">Investor</option></select></label></div><div class="two-col"><label>Annual gross income (${c.symbol})<input name="income" type="number" min="0" step="1" placeholder="0" required></label><label>Annual savings available (${c.symbol})<input name="savings" type="number" min="0" step="1" placeholder="0"></label></div>`;
  const extra = country==='BD' ? `<div class="two-col"><label>Eligible investment amount (${c.symbol}) <a href="${c.source}" target="_blank">reference</a><input name="deductions" type="number" min="0" placeholder="0"></label><label>Charity / approved donation (${c.symbol})<input name="charity" type="number" min="0" placeholder="0"></label></div>` : country==='IN' ? `<div class="two-col"><label>Eligible deductions such as 80C/80D (${c.symbol}) <a href="${c.source}" target="_blank">reference</a><input name="deductions" type="number" min="0" placeholder="0"></label><label>Regime<select name="regime"><option value="new">New regime preview</option><option value="old">Old regime preview</option></select></label></div>` : `<div class="two-col"><label>Filing status<select name="filing"><option value="single">Single</option><option value="married">Married filing jointly</option><option value="head">Head of household</option></select></label><label>Itemized/eligible deductions (${c.symbol}) <a href="${c.source}" target="_blank">reference</a><input name="deductions" type="number" min="0" placeholder="0"></label></div><div class="two-col"><label>Retirement/HSA contribution (${c.symbol})<input name="retirement" type="number" min="0" placeholder="0"></label><label>Charity donation (${c.symbol})<input name="charity" type="number" min="0" placeholder="0"></label></div>`;
  return `<div class="question-card"><div class="question-title"><h3>2. Income and filing category</h3><a href="${c.source}" target="_blank" rel="noopener">Law reference</a></div>${common}${extra}<label>Notes or special situation<textarea name="notes" rows="3" placeholder="Optional: dependents, multiple jobs, business expense notes, etc."></textarea></label></div>`;
}
function renderQuestions(){ const country=$('input[name="country"]:checked').value; $('#dynamicQuestions').innerHTML=getQuestions(country); $('#countryLaw').href=countryMeta[country].source; $('#previewCountry').textContent=countryMeta[country].name; }
function calcSlab(taxable, slabs){ let remaining=Math.max(0,taxable), tax=0, rows=[]; for(const [limit,rate] of slabs){ if(remaining<=0) break; const amount=Math.min(remaining, limit); const line=amount*rate; tax+=line; rows.push({amount,rate,line}); remaining-=amount; } return {tax,rows}; }
function calculate(form){ const data=Object.fromEntries(new FormData(form).entries()); const c=countryMeta[data.country]; const income=+data.income||0, savings=+data.savings||0, deductions=+data.deductions||0, retirement=+data.retirement||0, charity=+data.charity||0; let allowedDeduction=0, note=''; if(data.country==='BD'){ allowedDeduction=Math.min(deductions+charity, income*.20); note='Bangladesh preview applies a simplified allowance for eligible investment/donation up to 20% of income for demo purposes.'; } if(data.country==='IN'){ allowedDeduction=data.regime==='old'?Math.min(deductions,250000)+c.standardDeduction:c.standardDeduction; note=`India ${data.regime} regime preview with simplified deductions.`; } if(data.country==='US'){ const standard = data.filing==='married'?29200:data.filing==='head'?21900:c.standardDeduction; allowedDeduction=Math.max(standard, deductions+retirement+charity); note='USA preview compares a standard deduction assumption with provided deductions.'; } const taxable=Math.max(0,income-allowedDeduction); const slab=calcSlab(taxable,c.slabs); const effective=income?slab.tax/income*100:0; const potentialSavings=Math.min(savings, Math.max(0, income-taxable)); return {id:id(), country:data.country, countryName:c.name, taxYear:data.taxYear, input:data, income, savings, allowedDeduction, taxable, tax:slab.tax, effective, potentialSavings, rows:slab.rows, note, createdAt:new Date().toISOString(), source:c.source}; }
function renderResult(r){ const c=countryMeta[r.country]; $('#previewIncome').textContent=money(r.taxable,c); $('#previewTax').textContent=money(r.tax,c); $('#previewRate').textContent=r.effective.toFixed(2)+'%'; $('#previewSavings').textContent=money(r.potentialSavings,c); $('#heroProgress').style.width='100%'; $('#resultOutput').className='result-card'; $('#resultOutput').innerHTML=`<div><small>Total estimated tax</small><div class="result-total">${money(r.tax,c)}</div><p class="micro">${r.note}</p></div><div class="breakdown"><div class="break-row"><span>Gross income</span><strong>${money(r.income,c)}</strong></div><div class="break-row"><span>Allowed deduction / exemption preview</span><strong>${money(r.allowedDeduction,c)}</strong></div><div class="break-row"><span>Taxable income</span><strong>${money(r.taxable,c)}</strong></div><div class="break-row"><span>Effective tax rate</span><strong>${r.effective.toFixed(2)}%</strong></div></div><h3>Slab breakdown</h3><div class="breakdown">${r.rows.map(x=>`<div class="break-row"><span>${money(x.amount,c)} × ${(x.rate*100).toFixed(0)}%</span><strong>${money(x.line,c)}</strong></div>`).join('')}</div><div class="form-actions"><button class="primary" id="saveReportBtn" type="button">Save to profile</button><button class="secondary" id="pdfBtn" type="button">Download PDF</button></div><p class="micro">Reference: <a href="${r.source}" target="_blank" rel="noopener">${r.source}</a></p>`;
  $('#adviceOutput').className='advice-list'; $('#adviceOutput').innerHTML=recommendations(r).map(a=>`<div class="advice"><strong>${a.title}</strong><p>${a.text}</p><a href="${a.url}" target="_blank" rel="noopener">Open official / verified link</a></div>`).join(''); $('#saveReportBtn').onclick=()=>saveReport(r); $('#pdfBtn').onclick=()=>printPdf(r); }
function recommendations(r){ const c=countryMeta[r.country]; const low=r.savings < r.income*.1; return [{title:'Tax reduction check',text:r.allowedDeduction>0?'You already entered deduction/saving items. Keep proofs and verify limits before filing.':'You may check eligible deductions, retirement contributions or approved donations if applicable.',url:r.source},{title: low?'Build an emergency fund first':'Investment idea within savings',text:low?'Because savings look low, prioritize safe liquid savings before risk investments.':'Consider official/government-backed savings instruments or diversified regulated options within '+money(r.savings,c)+'.',url:investLinks[r.country]},{title:'Verified charity donation',text:'Donation benefits depend on approval status and country rules. Verify the organization before donating.',url:charityLinks[r.country]}]; }
function saveReport(r){ const u=currentUser(); if(!u) return openAuth('login'); const all=users(); const idx=all.findIndex(x=>x.id===u.id); all[idx].reports = all[idx].reports || []; all[idx].reports.unshift(r); save(STORAGE.users, all); updateAccountUI(); renderProfile(); alert('Report saved to your profile.'); }
function printPdf(r){ const c=countryMeta[r.country]; let div=$('.print-area'); if(!div){ div=document.createElement('div'); div.className='print-area'; document.body.appendChild(div); } div.innerHTML=`<h1>Personal CA Tax Report</h1><p><strong>Country:</strong> ${r.countryName}<br><strong>Tax year:</strong> ${r.taxYear}<br><strong>Generated:</strong> ${new Date(r.createdAt).toLocaleString()}</p><table><tr><th>Item</th><th>Amount</th></tr><tr><td>Gross income</td><td>${money(r.income,c)}</td></tr><tr><td>Allowed deduction preview</td><td>${money(r.allowedDeduction,c)}</td></tr><tr><td>Taxable income</td><td>${money(r.taxable,c)}</td></tr><tr><td>Total estimated tax</td><td>${money(r.tax,c)}</td></tr><tr><td>Effective rate</td><td>${r.effective.toFixed(2)}%</td></tr></table><h2>Slab breakdown</h2><table><tr><th>Taxable portion</th><th>Rate</th><th>Tax</th></tr>${r.rows.map(x=>`<tr><td>${money(x.amount,c)}</td><td>${(x.rate*100).toFixed(0)}%</td><td>${money(x.line,c)}</td></tr>`).join('')}</table><h2>References</h2><p>${r.source}</p><p><em>This report is for educational preview only and does not replace professional tax advice.</em></p>`; window.print(); }

function renderLaws(country='BD'){ $('#lawCards').innerHTML=laws[country].map(x=>`<article class="law-card"><h3>${x[0]}</h3><p>${x[1]}</p><a href="${x[2]}" target="_blank" rel="noopener">Open source</a></article>`).join(''); }
function openProfile(){ const u=currentUser(); if(!u) return openAuth('login'); renderProfile(); $('#profilePage').classList.remove('hidden'); document.body.style.overflow='hidden'; }
function closeProfile(){ $('#profilePage').classList.add('hidden'); document.body.style.overflow=''; }
function renderProfile(){ const u=currentUser(); if(!u) return; const reports=u.reports||[]; $('#profileTitle').textContent=`Welcome, ${u.fullName}`; $('#profileSubtitle').textContent=`@${u.username} · ${u.occupation} · ${u.email}`; $('#profile-overview').innerHTML=`<h2>Overview</h2><div class="dashboard-cards"><div class="dash-card"><small>Saved reports</small><strong>${reports.length}</strong></div><div class="dash-card"><small>Latest country</small><strong>${reports[0]?.countryName||'None'}</strong></div><div class="dash-card"><small>Total estimated tax</small><strong>${reports[0]?money(reports[0].tax,countryMeta[reports[0].country]):'—'}</strong></div></div><p class="micro">Use the calculator to create a new yearly tax report. Saved reports stay in this browser demo until you delete them.</p><div class="form-actions" style="justify-content:flex-start"><a class="primary" href="#calculator" id="profileCalcLink">New calculation</a></div>`; $('#profileCalcLink')?.addEventListener('click', closeProfile);
  $('#profile-reports').innerHTML=`<h2>Saved tax reports</h2>${reports.length?`<div class="report-list">${reports.map(rep=>`<article class="report-item"><div><strong>${rep.countryName} · ${rep.taxYear}</strong><p class="micro">${new Date(rep.createdAt).toLocaleString()} · Tax ${money(rep.tax,countryMeta[rep.country])} · Effective ${rep.effective.toFixed(2)}%</p></div><div class="report-actions"><button class="secondary" data-print="${rep.id}" type="button">Download PDF</button><button class="danger" data-delete="${rep.id}" type="button">Delete</button></div></article>`).join('')}</div>`:'<div class="empty-state">No saved reports yet.</div>'}`;
  $('#profile-account').innerHTML=`<h2>Account details</h2><div class="breakdown"><div class="break-row"><span>Full name</span><strong>${u.fullName}</strong></div><div class="break-row"><span>Occupation</span><strong>${u.occupation}</strong></div><div class="break-row"><span>Username</span><strong>@${u.username}</strong></div><div class="break-row"><span>Email</span><strong>${u.email}</strong></div><div class="break-row"><span>Created</span><strong>${new Date(u.createdAt).toLocaleDateString()}</strong></div></div>`;
  $('#profile-security').innerHTML=`<h2>Privacy & security</h2><div class="advice-list"><div class="advice"><strong>Password login enabled</strong><p>This demo stores a SHA-256 password hash in localStorage. In production, use Supabase Auth or a server backend with Argon2/bcrypt and never store passwords in browser storage.</p></div><div class="advice"><strong>Delete control</strong><p>You can delete each saved tax report from the Saved tax reports tab.</p></div><div class="advice"><strong>Production recommendation</strong><p>Use Supabase Row Level Security so every user can only read their own tax reports.</p></div></div>`;
  $$('[data-delete]').forEach(b=>b.onclick=()=>deleteReport(b.dataset.delete)); $$('[data-print]').forEach(b=>b.onclick=()=>{const rep=reports.find(r=>r.id===b.dataset.print); if(rep) printPdf(rep);}); }
function deleteReport(reportId){ const u=currentUser(); const all=users(); const idx=all.findIndex(x=>x.id===u.id); all[idx].reports=(all[idx].reports||[]).filter(r=>r.id!==reportId); save(STORAGE.users, all); renderProfile(); updateAccountUI(); }
function switchProfileTab(tab){ $$('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.profileTab===tab)); $$('.profile-pane').forEach(p=>p.classList.remove('active')); $('#profile-'+tab).classList.add('active'); }

function init(){ setTheme(load(STORAGE.theme,'dark')); renderQuestions(); renderLaws(); updateAccountUI(); $('#themeToggle').onclick=()=>setTheme(document.body.classList.contains('light')?'dark':'light'); $('#openAuth').onclick=()=>currentUser()?openProfile():openAuth('login'); $('#openAuthLarge').onclick=()=>currentUser()?openProfile():openAuth('login'); $('#heroLogin').onclick=()=>openAuth('login'); $('#profileBtn').onclick=openProfile; $('#closeProfile').onclick=closeProfile; $('#logoutBtn').onclick=logout; $('#profileLogout').onclick=logout; $('#closeAuth').onclick=closeAuth; $$('.auth-tabs .tab').forEach(b=>b.onclick=()=>switchAuth(b.dataset.authTab)); $('#registerForm').onsubmit=register; $('#loginForm').onsubmit=login; $$('input[name="country"]').forEach(r=>r.onchange=renderQuestions); $('#resetBtn').onclick=()=>{ $('#taxForm').reset(); renderQuestions(); $('#resultOutput').className='empty-state'; $('#resultOutput').textContent='No calculation yet.'; $('#adviceOutput').className='empty-state'; $('#adviceOutput').textContent='Recommendations appear after calculation.'; }; $('#taxForm').onsubmit=e=>{ e.preventDefault(); currentResult=calculate(e.currentTarget); renderResult(currentResult); location.hash='resultsSection'; }; $$('.law-tabs .tab').forEach(b=>b.onclick=()=>{ $$('.law-tabs .tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); renderLaws(b.dataset.lawTab); }); $$('.profile-tab').forEach(b=>b.onclick=()=>switchProfileTab(b.dataset.profileTab)); }
document.addEventListener('DOMContentLoaded', init);
